spring.application.name=birly-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/birlydb
spring.datasource.username=birly_user
spring.datasource.password=birlypass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect