spring.application.name=birly-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/billboard
spring.datasource.username=billboard_user
spring.datasource.password=changeme
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect